name: CI Tox
on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false  # If anything in the matrix fails, then everything queued and in-progress will canceled
      matrix:
        # Which environment and python versions to be runned on.
        os: [ubuntu macos windows]
        py: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox-gh
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Setup test suite
        run: tox r -vv --notest # r means run environments,  -vv verbose --notest skip invoking test commands.
      - name: Run test suite
        # --skip-pkg-install  skips installing the package
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
